Replace showMessage with Utilities.showMessage
issue because showMessage not defined in same js
TypeError: self.showMessage is not a function
    at Object.<anonymous> (VM16839 checkoutcom_flow.min.js:22:284)